### ISSUE TITLE
Data Analysis Goals and milestones

### ISSUE THREAD

**Issue by DaithiCarr** [DaithiCarr/Tasks#3]
**Overview of goals and milestones**

What do I want to achieve- whats the end goal 

Is there a standard I should achieve
```
```
How can I immediately make use of what I learn in order to keep it fresh

**Questions**
 - Is it Web Analytics or Data analyses ? 
- Web Analytics vs Data Analytics: Web analytics is data analytics that is restricted to your website. https://selecthub.com/business-analytics/web-analytics-vs-business-analytics/

Python vs SQL where to start
- [x] https://learn.onemonth.com/python-vs-sql-whats-the-difference/
- [ ] https://mode.com/blog/learning-python-sql

**Courses to do**
*SQL*
- [x] SQL & Database Design A-Z™: Learn MS SQL Server + PostgreSQL https://www.udemy.com/course/sqldatabases/learn/lecture/14404230?start=15#announcements

*General Data Science*
- [ ] Data Science A-Z™: Real-Life Data Science Exercises Included
 https://www.udemy.com/share/101WQoCEUTdl5VRHg=/

*Python*
- [ ] Python A-Z™: Python For Data Science With Real Exercises! 
https://www.udemy.com/share/101rOUCEUTdl5VRHg=/

*Java for Data Science*

Other possible courses down the road 
https://www.youtube.com/watch?v=UBbdWHCnn1o&feature=youtu.be
